[package]
name = "doukutsu-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
encoding_rs = "0.8.35"
glob = "0.3.3"
logos = {version="0.16.0", features=[]}
pico-args = "0.5.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
